main: com.mcrivals.prisonrankup.PrisonRankup
name: MCRivalsPrisonRankup
authors: [crepppy]
depends: [MCRivalsPrisonCore]
version: 1.0

commands:
  rankup:
    description: Ranks the player up to the next mine
    usage: /<command>
  mine:
    description: The admin mine command to configure the mines
    usage: /<command>
  thelp:
    description: Shows the given tutorial
    usage: /<command>
  prestige:
    description: Sends the player to an arena to fight their prestige boss
    usage: /<command>
  toggletutorials:
    description: Toggles a players tutorial preferences
    usage: /<command>

permissions:
  prisonrankup.mineadmin:
    description: Gives access to /mine command
    default: op