mins-until-quests-reset: 4320
current-quest: "blocks"
glass-colour: 4
placement-item:
 name: '&f&o{player} &6&l#{position}'
 lore:
  - ' '
  - '&fPlayer: &6&n{player}'
  - '&fAmount: &6&n{broken}'
  - '&fPosition: &6&n#{position}'
  - ' '
  
rewards:
 '1':
  - 'eco give {player} 1000'
 '2':
  - 'eco give {player} 500'
 '3':
  - 'eco give {player} 250'