name: RivalGlobalQuests
description: RivalGlobalQuests
author: Harley Swift
main: com.harley.mcrivals.RivalGlobalQuests
version: FINAL

commands:
 globalquests:
  description: Main GUI Command
  usage: /globalquests